#ifndef CONFIG_H
#define CONFIG_H

#define MAP_LEAST_COUNT 0.1 // in meters

#define CURRENT_ROBOT_COLOR 255
#define PREVIOUS_ROBOT_TRAJECTORY_COLOR 180

// #define OBSTACLE_COLOR 127
// #define EXPLORED_AREA_COLOR 30

#define OBSTACLE_COLOR 64
#define EXPLORED_AREA_COLOR 128

#endif